on:
  push:
    branches: master

name: test

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@master
      - uses: r-lib/actions/setup-r@master
        with:
          r-version: '3.6.2' 
          
      - name: Install packages
        run: |
          install.packages("tidyverse")
          install.packages("here")
          install.packages("yaml")
          install.packages("vroom")
        shell: Rscript {0}

      - uses: actions/cache@v1
        with:
          path: ~/Library/Application Support/renv
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-

      - run: Rscript scripts/update.R
      
      - name: Commit results
        run: |
          git commit now.txt -m 'write file (on push)' || echo "No changes to commit"
          git push https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git HEAD:${{ github.ref }} || echo "No changes to commit"
