on:
  push:
    branches: master

name: test

jobs:
  test:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@master
      - uses: r-lib/actions/setup-r@master
        with:
          r-version: '3.6.2'
          
      - name: Install packages
        run: |
          Rscript -e 'install.packages("readr")' \
                  -e 'remotes::install.packages("tibble")' \

      - run: Rscript now.R
